<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="121020" started-at="2018-10-02T15:22:29Z" finished-at="2018-10-02T15:24:30Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="121020" started-at="2018-10-02T15:22:29Z" finished-at="2018-10-02T15:24:30Z">
      <class name="com.appium.tests.Tester">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.appium.tests.Tester@67f89fa3]" name="beforeClass" is-config="true" duration-ms="108670" started-at="2018-10-02T20:52:29Z" finished-at="2018-10-02T20:54:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testSearch()[pri:0, instance:com.appium.tests.Tester@67f89fa3]" name="testSearch" duration-ms="11983" started-at="2018-10-02T20:54:18Z" finished-at="2018-10-02T20:54:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at com.appium.tests.Tester.testSearch(Tester.java:99)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSearch -->
        <test-method status="PASS" signature="AfterClass()[pri:0, instance:com.appium.tests.Tester@67f89fa3]" name="AfterClass" is-config="true" duration-ms="327" started-at="2018-10-02T20:54:30Z" finished-at="2018-10-02T20:54:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterClass -->
      </class> <!-- com.appium.tests.Tester -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
